#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <old_name> <new_name>"
    exit 1
fi

old_name=$1
new_name=$2
remote=origin

git fetch --all

git push $remote $remote/$old_name:refs/heads/$new_name :$old_name

git fetch --all
